[project]
name = "machine-learning-zoomcamp-2026-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "reema", email = "reema.burne@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
machine-learning-zoomcamp-2026-homework = "machine_learning_zoomcamp_2026_homework:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
